### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by Futiax** [luktvpl/minecraft-er-cpp#1]
Hello, I would like to know if you have a compiled version of the code, because when I try to compile it on my side it displays an error.

Thanks in advance, Futiax

**Comment by thenameisluk** [comment]
i have compiled version for windows and alpine linux x86

**Comment by Futiax** [comment]
Could you please send me the windows version?

**Comment by thenameisluk** [comment]
the latest version is not compiled for windows (only on linux) and i can't compile it now but if you send me the error your getting i'll try to help you

**Comment by Futiax** [comment]
https://user-images.githubusercontent.com/79416461/187044040-d55f8d55-f285-4ab6-b0aa-00b70214438c.mp4

**Comment by thenameisluk** [comment]
first you should change all emotes (example : <:00:976014562996391936>)
in main.cpp on line 446-448 and 477-510 to emotes in your serwer
if you want to download them you should
<:name:id> -> https://cdn.discordapp.com/emojis/id.png (replace id with number)

if you want to get this (<:name:id>) you can copy massage with custom emoji on mobile device
or make bot that logs every message to console and then send emoji

go to folder in terminal and then : 
mkdir build
cd build
cmake ..
cmake --build .

than cmake project should build
after compilation you should copy
dll's from lib folder to the same folder as exe file
add token.txt file and put bot token inside
than run the bot

**Comment by Futiax** [comment]
Thanks

**Comment by Futiax** [comment]
![image](https://user-images.githubusercontent.com/79416461/188281161-006d02cf-86f5-439b-9714-a07bd5fffefb.png)
I don’t know very well how to use cmake, and as you can see, there is still a mistake, it would be possible to have the means to resolve this errreur.

**Comment by thenameisluk** [comment]
i think you don't have compiler installed

**Comment by thenameisluk** [comment]
you should instal
visual studio comunity : https://visualstudio.microsoft.com
with c++ selected 
![image](https://user-images.githubusercontent.com/92756992/188282465-fea9fd4b-d89b-44bd-9608-b20b07714fea.png)
and open project in
vscode : https://code.visualstudio.com
install https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack extension pack
than open cmakelist.txt in vscode and click build button 
![image](https://user-images.githubusercontent.com/92756992/188282541-21b705a7-c861-4000-9c71-e80b438c7879.png)
if it asks you for compiler select 
![image](https://user-images.githubusercontent.com/92756992/188282560-3d314cce-4391-46db-97de-e60495b0c3d3.png)
and it should build automaticaly
than create usr.txt and token.txt (paste token in it)
than move dll files from build/libs/dpp/liblary to the same folder exe file is and run.

**Comment by Futiax** [comment]
I still can’t compile it full of errors, could you please send me a compiled version?

**Comment by thenameisluk** [comment]
I'll send you compiled version if you send me assets (emoji in format <name:id>) that are in your server because if i compile it with my emojis your bot won't be able to use them.

**Comment by Futiax** [comment]
I used the same emoji code as on your server

**Comment by thenameisluk** [comment]
But discord bot can only use emojis from server it's in. If you try to use emoji from my server it won't work.

**Comment by Futiax** [comment]
i add your emoji on my server and i use same code

**Comment by thenameisluk** [comment]
But that's not how the discord works i need to have ids of emojis on your serwer

**Comment by Futiax** [comment]
> But that's not how the discord works i need to have ids of emojis on your serwer

how to get this id ?

**Comment by thenameisluk** [comment]
You send all emojis in one messege (in order) and then you copy the content of message on mobile discord app. You can find all emojis that bot uses in emoji folder inside repo. But there is no player emoji so you have to obtain one on your on.

**Comment by Futiax** [comment]
<:p00:1015647209313808434><:p01:1015647211784241252><:p02:1015647214661546095><:31:1015647189738987581><:02:1015647123997462652><:00:1015647120314867712><:01:1015647122428805130><:03:1015647206230986870><:04:1015647126908326019><:05:1015647128925778022><:06:1015647131106803752><:07:1015647132918743153><:08:1015647135699582978><:09:1015647139025662014><:10:1015647141185724428><:11:1015647143576477807><:12:1015647145937879150><:13:1015647147674320897><:14:1015647150580969522><:15:1015647152963338370><:16:1015647155249225748><:17:1015647157442842746><:18:1015647159653236756><:19:1015647162144669716><:20:1015647164606709831><:21:1015647167232360558><:22:1015647169346277417><:23:1015647172156461087><:24:1015647174220066876><:25:1015647175998447751><:26:1015647178418557088><:27:1015647180662521898><:28:1015647182969389126><:29:1015647185452412960><:30:1015647187604099152><:32:1015647191710318644><:33:1015647201982173319> 

same first code and p00 p01 p02 is player skin

**Comment by thenameisluk** [comment]
[bot.zip](https://github.com/luktvpl/minecraft-er-cpp/files/9592445/bot.zip)
you have to put your bot token in token.txt

**Comment by Futiax** [comment]
Thanks for your help
